import type { Metadata } from "next";
import { Geist, Geist_Mono, Archivo } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";
import Navbar from "./components/Navbar";
import LenisProvider from "@/components/LenisProvider";
import ResponsiveReloadWrapper from "@/components/ResponsiveReloadWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Sky Jets",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${archivo.variable}`}>
        <ResponsiveReloadWrapper>
          <LenisProvider>
            <Navbar />
            {children}
          </LenisProvider>
        </ResponsiveReloadWrapper>
      </body>
    </html>
  );
}
